In [1]:
import numpy as np 

In [5]:
a = np.random.randint(0,100,20)
print(a)

[45 13 88  3 50 78 87  1 38 98  9 56 22 66 68 20 66 69 18 68]


In [3]:
a % 2 == 0.

array([False, False, False, False,  True, False, False, False, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False,  True])

In [7]:
a[ a % 2 == 0]

array([88, 50, 78, 38, 98, 56, 22, 66, 68, 20, 66, 18, 68])

In [10]:
a[ (a%2 == 0 ) & (a>50)]

array([88, 78, 98, 56, 66, 68, 66, 68])

In [11]:
a[(a % 2 == 0 )  | (a>50)]

array([88, 50, 78, 87, 38, 98, 56, 22, 66, 68, 20, 66, 69, 18, 68])

In [15]:
p = np.random.randint(1,999,100)
p

array([345, 454, 597, 933, 863, 839, 856, 866, 920, 243, 122, 655, 591,
       700, 124,  81, 542, 724, 648,  19, 776, 670, 990, 654, 425, 736,
       463, 627, 227, 393, 167, 618, 805, 998, 563, 552, 237, 978, 700,
        37, 882, 152, 787, 481, 229, 314, 248, 561, 515, 424, 542, 822,
       547, 497, 566, 928, 572, 511, 549, 683, 675, 598, 819, 592, 933,
        59, 958, 243, 472, 646, 162, 519, 734, 686, 948, 105, 617, 958,
       674, 268, 132,  64,  44, 256, 271, 630, 338, 608, 337, 604, 607,
       190, 806,  47, 374, 120, 755, 558, 843, 748])

In [13]:
p % 10 == 9 #หาเลขที่ลงท้ายด้วย. 9

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False])

In [16]:
p[ p % 10 == 9 ]

array([839,  19, 229, 549, 819,  59, 519])

In [17]:
np.where(p % 10 == 9)

(array([ 5, 19, 44, 58, 62, 65, 71]),)

In [18]:
print('Hello world')

Hello world
