In [2]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.20.1


In [4]:
a = np.reshape(np.arange(1,9),(4,2))
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
b = np.reshape(np.arange(1,9)*20, (4,2))
b

array([[ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [8]:
np.vstack((a,b)) # การ stack ในแนว vertical

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [9]:
c = np.reshape(np.arange(1,9)*11,(4,2))
c

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [11]:
np.vstack((a,b,c))

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160],
       [ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88]])

In [17]:
d = np.hstack((a,b,c)) # Horizontal stack
d

array([[  1,   2,  20,  40,  11,  22],
       [  3,   4,  60,  80,  33,  44],
       [  5,   6, 100, 120,  55,  66],
       [  7,   8, 140, 160,  77,  88]])

In [22]:
#Split
e = np.hsplit(d , 3 ) #แบ่ง d ตามแนว Horizontal เป็น 3 array แยกออกไป
e

[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 20,  40],
        [ 60,  80],
        [100, 120],
        [140, 160]]),
 array([[11, 22],
        [33, 44],
        [55, 66],
        [77, 88]])]

In [23]:
e[0]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
e[1]

array([[ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [28]:
f = np.vsplit(d,2)
f

[array([[ 1,  2, 20, 40, 11, 22],
        [ 3,  4, 60, 80, 33, 44]]),
 array([[  5,   6, 100, 120,  55,  66],
        [  7,   8, 140, 160,  77,  88]])]

In [29]:
f[0]

array([[ 1,  2, 20, 40, 11, 22],
       [ 3,  4, 60, 80, 33, 44]])

In [30]:
f[1]

array([[  5,   6, 100, 120,  55,  66],
       [  7,   8, 140, 160,  77,  88]])

In [31]:
#1-dim

In [33]:
a = np.arange(1,11) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b = np.arange(1,11) * 50
b

array([ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500])

In [36]:
np.vstack((a,b))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]])

In [37]:
np.hstack((a,b))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  50, 100, 150,
       200, 250, 300, 350, 400, 450, 500])

In [38]:
np.stack((a,b), axis = 1)

array([[  1,  50],
       [  2, 100],
       [  3, 150],
       [  4, 200],
       [  5, 250],
       [  6, 300],
       [  7, 350],
       [  8, 400],
       [  9, 450],
       [ 10, 500]])