In [2]:
import numpy as np 
print(f'numpy version = {np.__version__}')

numpy version = 1.20.1


In [3]:
# การทำ boardcasting คือการนำ array ที่ขนาดไม่เท่ากันมาทำ operation กัน ได้
np.random.seed(9)
x = np.random.randint ( 1, 11 , 5)
x


array([6, 7, 9, 7, 2])

In [4]:
x * 2

array([12, 14, 18, 14,  4])

In [8]:
b=np.array([2,2,2,2,2])


In [9]:
x * b

array([12, 14, 18, 14,  4])

In [10]:
x * np.array([2])

array([12, 14, 18, 14,  4])

In [12]:
np.repeat(np.array([2]),5)

array([2, 2, 2, 2, 2])

In [14]:
x * np.repeat(np.array([2]),5)

array([12, 14, 18, 14,  4])

In [19]:
me = np.mean(x)
std = np.std(x)
print(me)
print(std)

6.2
2.3151673805580453


In [21]:
z = (x - me) / std
z

array([-0.08638684,  0.34554737,  1.2094158 ,  0.34554737, -1.81412369])

In [22]:
## Array 2 D


In [24]:
a = np.arange(1 , 7 ).reshape(3,2) * 10 
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [25]:
a.shape

(3, 2)

In [26]:
5 + a 

array([[15, 25],
       [35, 45],
       [55, 65]])

In [30]:
# b = np.full((3,2),5)
b = np.full((a.shape),5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [31]:
a + b

array([[15, 25],
       [35, 45],
       [55, 65]])

In [33]:
c = np.array([2,10])
c

array([ 2, 10])

In [36]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [34]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [35]:
print (a.shape)
print(c.shape)

#ถ้าขนาดของ array ไม่เท่ากัน มันจะพยายาม เพิ่ม colum ให้เป็นเลขที่เยอะสุด และจะเพิ่ม ROW ให้เป็นเลขที่เยอะสุด
#ในที่นี้ a = (3,2) c = (1,2) มันจะพยายามปรับ cเป็น (3,2)

(3, 2)
(2,)


In [43]:
#np.tile(c,3) #repeat 3 ครัั้ง 
np.tile(c,a.shape[0]).reshape(a.shape)

array([[ 2, 10],
       [ 2, 10],
       [ 2, 10]])

In [52]:
print(a)
np.shape(a)

[[10 20]
 [30 40]
 [50 60]]


(3, 2)

In [50]:
d = np.array([[2],[3],[4]])
print(d)
np.shape(d)

[[2]
 [3]
 [4]]


(3, 1)

In [60]:
print(a+d)

print(np.shape(a))
print(np.shape(d))
np.shape(a+d)

[[12 22]
 [33 43]
 [54 64]]
(3, 2)
(3, 1)


(3, 2)

In [62]:
e = np.array([[5],[10]])
e

array([[ 5],
       [10]])

In [63]:
print(a.shape)
print(e.shape)

(3, 2)
(2, 1)


In [64]:
a + e # จะทำไม่ได้ ต้องมี colum หรือ row เท่ากันหนึ่งด้าน

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 