In [12]:
!pip3 install scipy
import numpy as np 
print(f'numpy version = {np.__version__}')

numpy version = 1.20.1


In [2]:
w = np.array([70,48,52,60,52])
print(w)

[70 48 52 60 52]


In [3]:
w.size

5

In [4]:
np.min(w)

48

In [6]:
np.max(w)

70

In [7]:
np.sum(w)

282

In [8]:
np.mean(w)

56.4

In [9]:
np.median(w)

52.0

In [10]:
np.sort(w)

array([48, 52, 52, 60, 70])

In [ ]:
from scipy import stats 

In [18]:
m = stats.mode(w)
m

ModeResult(mode=array([52]), count=array([2]))

In [19]:
m[0]

array([52])

In [20]:
m[0][0]

52

In [21]:
m[1][0]

2

In [23]:
np.sort(w)

array([48, 52, 52, 60, 70])

In [24]:
w

array([70, 48, 52, 60, 52])

In [26]:
w2 = np.sort(w)[: : -1]
w2

array([70, 60, 52, 52, 48])

In [27]:
w

array([70, 48, 52, 60, 52])

In [28]:
w.sort() ## ทำแบบนี้คือการเปลี่ยนค่า w ไปเลย

In [29]:
w

array([48, 52, 52, 60, 70])

In [30]:
# 2-DIM array

In [32]:
a = np.reshape(np.arange(1,21),(4,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
np.mean(a) #มันจะมองว่า เป็น array 1 มิติ


10.5

In [34]:
a.size

20

In [35]:
a.shape

(4, 5)

In [36]:
np.mean(a[0])

3.0

In [37]:
np.mean(a[:,1])

9.5

In [38]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
np.mean(a , axis = 0) #พิจารณาคิดในแต่ละแถว #axis = 0 : vertical line #axis = 1 : horizontal line 

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [41]:
np.mean(a , axis= 1)

array([ 3.,  8., 13., 18.])

In [42]:
np.sum ( a ,axis = 0)

array([34, 38, 42, 46, 50])

In [43]:
np.std(a , axis = 0)

array([5.59016994, 5.59016994, 5.59016994, 5.59016994, 5.59016994])

In [44]:
np.ptp(a) #peak to peak 

19