In [1]:
import numpy as np 
print(f'numpy version = {np.__version__}')

numpy version = 1.20.1


In [3]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
b = a.reshape(3,-1)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
b.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [12]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
# TILE
d = np.array([2,1,8])
d

array([2, 1, 8])

In [15]:
np.tile(d , 3)

array([2, 1, 8, 2, 1, 8, 2, 1, 8])

In [16]:
np.tile(d,(3,1))

array([[2, 1, 8],
       [2, 1, 8],
       [2, 1, 8]])

In [17]:
e = np.array([[1,2],[10,20]])
e

array([[ 1,  2],
       [10, 20]])

In [19]:
np.tile(e,(2,3))

array([[ 1,  2,  1,  2,  1,  2],
       [10, 20, 10, 20, 10, 20],
       [ 1,  2,  1,  2,  1,  2],
       [10, 20, 10, 20, 10, 20]])

In [20]:
np.tile([[4,7],[8,9]],(4,3))

array([[4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9]])

In [22]:
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# Repeat 

In [24]:
np.repeat(9,3)

array([9, 9, 9])

In [26]:
np.repeat([10,15,20],2)

array([10, 10, 15, 15, 20, 20])

In [27]:
np.tile([10,15,20],2)

array([10, 15, 20, 10, 15, 20])

In [28]:
g = np.array([[1,2],[8,9]])
g

array([[1, 2],
       [8, 9]])

In [29]:
np.repeat(g,3)

array([1, 1, 1, 2, 2, 2, 8, 8, 8, 9, 9, 9])

In [30]:
g.ravel() 

array([1, 2, 8, 9])

In [32]:
np.repeat(g.ravel(),3)

array([1, 1, 1, 2, 2, 2, 8, 8, 8, 9, 9, 9])