In [1]:
import numpy as np 
print(f'numpy version = {np.__version__}')

numpy version = 1.20.1


In [2]:
# 1-dim array 

In [4]:
a = np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
a[2] #การเข้าด้วย index 
a[5]

50

In [6]:
a[-1]

90

In [7]:
a[:3] #การเข้าแบบ Slice 

array([ 0, 10, 20])

In [8]:
a[3:5]

array([30, 40])

In [9]:
a[3:]

array([30, 40, 50, 60, 70, 80, 90])

In [10]:
a[3:6] #การเอาตัวที่ 3 ถึงตัวที 5

array([30, 40, 50])

In [11]:
a[: :2] # ตัวแรกถึงตัวสุดท้าย skip ทีละ 2

array([ 0, 20, 40, 60, 80])

In [12]:
a[-4 : -1 ]

array([60, 70, 80])

In [14]:
a[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])