In [4]:
import numpy as np 
print(f'Numpy version = {np.__version__}')

Numpy version = 1.20.1


In [5]:
# การอ่านจาก array 2 มิติ
a = np.reshape(np.arange(1 , 21),(4,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
a[1] #จะเอาแถวที่ 1 

array([ 6,  7,  8,  9, 10])

In [7]:
a[3]

array([16, 17, 18, 19, 20])

In [8]:
a[-1]

array([16, 17, 18, 19, 20])

In [9]:
# หากต้องการเลข 8 หมายความว่า row 1 colum 2 
# ต้องนับแถวแรกเป็น 0 เสมอ 
a[1,2]

8

In [10]:
a[1][2]


8

In [9]:
list(np.ndenumerate(a))
#บอกพิกัด #บอกค่าที่พิกัดนั้นๆ 

[((0, 0), 1),
 ((0, 1), 2),
 ((0, 2), 3),
 ((0, 3), 4),
 ((0, 4), 5),
 ((1, 0), 6),
 ((1, 1), 7),
 ((1, 2), 8),
 ((1, 3), 9),
 ((1, 4), 10),
 ((2, 0), 11),
 ((2, 1), 12),
 ((2, 2), 13),
 ((2, 3), 14),
 ((2, 4), 15),
 ((3, 0), 16),
 ((3, 1), 17),
 ((3, 2), 18),
 ((3, 3), 19),
 ((3, 4), 20)]

In [11]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
a[0:2]
# array[start:stop:step]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
a[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
a[:,2]

array([ 3,  8, 13, 18])

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [18]:
a[:,3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [19]:
a[:,-1]

array([ 5, 10, 15, 20])

In [11]:
a[: : 2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])